"""empty message

Revision ID: 152bf0a231f0
Revises: ba5f13313e88
Create Date: 2019-02-08 16:46:25.141830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152bf0a231f0'
down_revision = 'ba5f13313e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lockers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('lockers_user_fkey', 'lockers', type_='foreignkey')
    op.create_foreign_key(None, 'lockers', 'users', ['user_id'], ['id'])
    op.drop_column('lockers', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lockers', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lockers', type_='foreignkey')
    op.create_foreign_key('lockers_user_fkey', 'lockers', 'users', ['user'], ['id'])
    op.drop_column('lockers', 'user_id')
    # ### end Alembic commands ###
