"""empty message

Revision ID: 1e9b3581c92d
Revises: 02a9c9e68bc7
Create Date: 2019-01-22 13:13:07.433070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9b3581c92d'
down_revision = '02a9c9e68bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('category', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('location', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'location')
    op.drop_column('requests', 'category')
    # ### end Alembic commands ###
